version: '3.8'

name: footballscoreboard_app_compose

services:
  db:
    container_name: footballscoreboard_db
    image: mysql:8.0.28
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: football_dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: football_db
    volumes:
      - path/to/mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - appnet

  api:
    container_name: footballscoreboard_api
    build:
      context: src
      dockerfile: src/Hosts/Api/Dockerfile
    ports:
      - 5001:80
    environment:
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/key.pem
      Cors__PolicyName: WebClientCorsPolicy
      Cors__AllowedOrigins: https://localhost
      Cors__AllowedMethods: GET

  #worker:
  #  build: ../src/Worker/Worker.Game
  #  entrypoint: [ "sh", "-c", "sleep 1m; dotnet Worker.Game.dll" ]
  #  image: worker:latest
  #  networks:
  #    - DOTNET_ENVIRONMENT=Production
  #  depends_on:

networks:
  app:
    driver: bridge
