version: "3.8"

name: footballscoreboard_db_compose

services:
  db:
    container_name: footballscoreboard_db
    image: mysql:8.0.28
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: footballscoreboard_db
    env_file:
      - .env.db
    volumes:
      - ./data/appdb:/var/lib/mysql
      - ./scripts/appdb:/docker-entrypoint-initdb.d
    networks:
      - db_net

  db_viewer:
    container_name: footballscoreboard_db_viewer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db_net
    depends_on:
      - db

networks:
  db_net:
    driver: bridge
