version: "3.8"

services:
  appdb:
    container_name: footballscoreboard_appdb
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: football_db
    volumes:
      - path/to/mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - db

  appdb_viewer:
    container_name: footballscoreboard_appdb_viewer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db
    depends_on:
      - db

networks:
  db:
    driver: bridge
