version: '3.8'

name: footballscoreboard_app_compose

services:
  db:
    container_name: footballscoreboard_db
    image: mysql:8.0.28
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: football_db
    env_file:
      - db.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - appnet

  api:
    container_name: footballscoreboard_api
    build:
      context: .
      dockerfile: src/Hosts/Api/Dockerfile
      tags:
        - rolspace/footballscoreboard_api:dev
    ports:
      - 5001:443
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/key.pem
      Cors__PolicyName: WebClientCorsPolicy
      Cors__AllowedOrigins: https://localhost
      Cors__AllowedMethods: GET
    env_file:
      - app.env
    depends_on:
      - db
    networks:
      - appnet

  blazor:
    container_name: footballscoreboard_blazor
    image: nginx
    build:
      context: .
      dockerfile: src/Hosts/Blazor/Dockerfile
      tags:
        - rolspace/footballscoreboard_blazor:dev
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - api

  worker:
    container_name: footballscoreboard_worker
    build:
      context: .
      dockerfile: src/Hosts/Worker/Dockerfile
      tags:
        - rolspace/footballscoreboard_worker:dev
    ports:
      - 5003:443
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 5003
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/key.pem
      Hub__HubUrl: https://footballscoreboard_api/hub/v1/plays
    env_file:
      - app.env
    depends_on:
      - db
      - api
      - blazor
    networks:
      - appnet
    entrypoint: [ "sh", "-c", "sleep 1m; dotnet Football.Worker.dll" ]

networks:
  appnet:
    driver: bridge
