version: "3.8"

name: footballscoreboard_db_compose

services:
  db:
    container_name: footballscoreboard_db
    image: mysql:8.0.28
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: football_dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: football_db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - dbnet

  db_viewer:
    container_name: footballscoreboard_db_viewer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - dbnet
    depends_on:
      - db

networks:
  dbnet:
    driver: bridge
