version: '3.8'

services:

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /path/mysql:/var/lib/mysql
    networks:
      - app

  web:
    build: ../src/Dashboard/Dashboard.Server
    image: dashboard:latest
    ports:
      - 5001:80
    networks:
      - app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  worker:
    build: ../src/Worker/Worker.Game
    entrypoint: ["sh", "-c", "sleep 1m; dotnet Worker.Game.dll"]
    image: worker:latest
    networks:
      - app
    environment:
      - DOTNET_ENVIRONMENT=Production
    depends_on:
      - db
      - web

networks:
  app:
    driver: bridge
