using DotNet.Testcontainers.Configurations;
using Microsoft.AspNetCore.Mvc.Testing;
using Npgsql;
using Testcontainers.PostgreSql;

namespace Football.Api.IntegrationTests.Fixtures;

public class ApiIntegrationTestFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _dbContainer = new PostgreSqlBuilder()
        .WithImage("postgres:17")
        .Build();

    private WebApplicationFactory<Program> _factory = null!;

    public HttpClient HttpClient { get; private set; } = null!;

    public IServiceProvider Services => _factory.Services;

    public async Task InitializeAsync()
    {
        await _dbContainer.StartAsync();

        await SeedDatabaseAsync();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseSetting("ConnectionStrings:FootballDbConnection", _dbContainer.GetConnectionString());
                builder.UseSetting("Scoreboard:Week", "1");
            });

        HttpClient = _factory.CreateClient();
    }

    public async Task DisposeAsync()
    {
        HttpClient.Dispose();
        await _factory.DisposeAsync();
        await _dbContainer.DisposeAsync();
    }

    private async Task SeedDatabaseAsync()
    {
        string seedSqlPath = Path.Combine(AppContext.BaseDirectory, "footballscoreboard_testdb.sql");
        byte[] seedSqlBytes = await File.ReadAllBytesAsync(seedSqlPath);

        // Copy the SQL file into the container and execute it via psql.
        // NpgsqlCommand cannot handle COPY ... FROM stdin statements generated by pg_dump;
        // running psql inside the container is the correct approach for pg_dump output.
        const string containerSqlPath = "/tmp/seed.sql";
        await _dbContainer.CopyAsync(seedSqlBytes, containerSqlPath, UnixFileModes.UserRead | UnixFileModes.UserWrite);

        NpgsqlConnectionStringBuilder csb = new(_dbContainer.GetConnectionString());
        await _dbContainer.ExecAsync(new[]
        {
            "psql",
            "--username", csb.Username!,
            "--dbname", csb.Database!,
            "--file", containerSqlPath
        });
    }
}
